# Generated by Django 5.0.6 on 2024-06-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Score',
            new_name='score',
        ),
    ]
