# Generated by Django 5.0.6 on 2024-06-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_score_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_champion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='is_finalist',
            field=models.BooleanField(default=False),
        ),
    ]
